/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterfaz;

import CapaMundo.Farmacia;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author USUARIO
 */
public class Publicacion extends javax.swing.JDialog {
    
    //Componente del  fondo de pantalla.
    FondoPanel fondo = new FondoPanel();
    
    //declaro el enlace.
    private Farmacia puente;
    int indice = 0;

    /**
     * Creates new form Publicacion
     */
    public Publicacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        //Componente del  fondo de pantalla.
        this.setContentPane(fondo);
        
        initComponents();
        //creo el enlace.
        puente = new Farmacia();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnPrimero = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        txtPresentacionP = new javax.swing.JTextField();
        txtMedicamentoP = new javax.swing.JTextField();
        txtCostoP = new javax.swing.JTextField();
        BtnSiguiente = new javax.swing.JButton();
        BtnUltimo = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTiempoP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRutaP = new javax.swing.JTextField();
        FotoP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        BtnPrimero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnPrimero.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ultimo_pequeño.png"))); // NOI18N
        BtnPrimero.setText("Primero");
        BtnPrimero.setContentAreaFilled(false);
        BtnPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPrimero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ultimo_pequeño.png"))); // NOI18N
        BtnPrimero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ultimo_grande.png"))); // NOI18N
        BtnPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrimeroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medicamento");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Presentacion");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("costo");

        txtCodigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPActionPerformed(evt);
            }
        });

        txtPresentacionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresentacionPActionPerformed(evt);
            }
        });

        txtMedicamentoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicamentoPActionPerformed(evt);
            }
        });

        txtCostoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoPActionPerformed(evt);
            }
        });

        BtnSiguiente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente_Pequeño.png"))); // NOI18N
        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.setContentAreaFilled(false);
        BtnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente_Pequeño.png"))); // NOI18N
        BtnSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente_Grande.png"))); // NOI18N
        BtnSiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        BtnUltimo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnUltimo.setForeground(new java.awt.Color(255, 255, 255));
        BtnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/primero_pequeño.png"))); // NOI18N
        BtnUltimo.setText("Ultimo");
        BtnUltimo.setContentAreaFilled(false);
        BtnUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnUltimo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/primero_pequeño.png"))); // NOI18N
        BtnUltimo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/primero_grande.png"))); // NOI18N
        BtnUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUltimoActionPerformed(evt);
            }
        });

        BtnAnterior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnAnterior.setForeground(new java.awt.Color(255, 255, 255));
        BtnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior_pequeña.png"))); // NOI18N
        BtnAnterior.setText("Anterior");
        BtnAnterior.setContentAreaFilled(false);
        BtnAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnAnterior.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior_pequeña.png"))); // NOI18N
        BtnAnterior.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior_Grande.png"))); // NOI18N
        BtnAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tiempo");

        txtTiempoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoPActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ruta");

        txtRutaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaPActionPerformed(evt);
            }
        });

        FotoP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTiempoP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtRutaP, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(txtMedicamentoP)
                                    .addComponent(txtCostoP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPresentacionP, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(BtnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(117, 117, 117)
                .addComponent(FotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigoP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMedicamentoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPresentacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCostoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTiempoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRutaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(FotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrimeroActionPerformed
        // TODO add your handling code here:
        if(puente.DarNumerodeMedicamentos()==0){
            
        }else{
            indice=0;
        Indice(indice);
        
        
        }
        
        
    }//GEN-LAST:event_BtnPrimeroActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // TODO add your handling code here:
        if(puente.DarNumerodeMedicamentos()==0){
            
        }else{
            indice++;
        if(indice == puente.DarNumerodeMedicamentos()){
            indice--;
        }
        Indice(indice);
        
        
        }
        
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUltimoActionPerformed
        // TODO add your handling code here:
        if(puente.DarNumerodeMedicamentos()==0){
            
        }else{
           int Numero = puente.DarNumerodeMedicamentos()-1;
        Indice(Numero);
        indice = puente.DarNumerodeMedicamentos()-1;
        
        
        }
        
    }//GEN-LAST:event_BtnUltimoActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        // TODO add your handling code here:
        if(puente.DarNumerodeMedicamentos()==0){
            
        }else{
             if(indice == 0){
            indice++;
        }
        indice--;
        Indice(indice);
        
       
        }
       
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void txtCodigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodigoPActionPerformed

    private void txtMedicamentoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicamentoPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMedicamentoPActionPerformed

    private void txtPresentacionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresentacionPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPresentacionPActionPerformed

    private void txtCostoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCostoPActionPerformed

    private void txtTiempoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTiempoPActionPerformed

    private void txtRutaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaPActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRutaPActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //el siguiente metodo me permite almacenar todo en un solo boton y apartir de este lo llamo para cada uno.
    private void Indice(int indice){
         
    txtCodigoP.setText(puente.DarCodigoMedicamento(indice)+"");
    txtMedicamentoP.setText(puente.DarNombreMedicamento(indice));
    txtPresentacionP.setText(puente.DarPresentacion(indice));
    txtCostoP.setText(puente.DarCosto(indice)+"");
    txtTiempoP.setText(puente.DarTiempo(indice)+"");
    txtRutaP.setText(puente.Darruta(indice));
    
     File archivo = new File(puente.Darruta(indice));
       rsscalelabel.RSScaleLabel.setScaleLabel(FotoP,puente.Darruta(indice));
       
        //los sigientes comandos permiten que no se pueda digitar en las cajas de texto.  
        
        txtCodigoP.setFocusable(false);
        txtMedicamentoP.setFocusable(false);
        txtPresentacionP.setFocusable(false);
        txtCostoP.setFocusable(false);
        txtTiempoP.setFocusable(false);
        txtRutaP.setFocusable(false);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Publicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Publicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Publicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Publicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Publicacion dialog = new Publicacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnPrimero;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton BtnUltimo;
    private javax.swing.JLabel FotoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtCostoP;
    private javax.swing.JTextField txtMedicamentoP;
    private javax.swing.JTextField txtPresentacionP;
    private javax.swing.JTextField txtRutaP;
    private javax.swing.JTextField txtTiempoP;
    // End of variables declaration//GEN-END:variables

    
    //Metodo para el fondo de Pantalla.
    class FondoPanel extends JPanel{
        private Image imagen;
        
        
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Imagenes/brillo.jpg")).getImage();
           
           g.drawImage(imagen,0,0, getWidth(), getHeight(), this);
           
            setOpaque(false);
            
            super.paint(g);
        }
    }
}
